title: Jack Shaw
description: Personal academic website of Jack Shaw, Postdoctoral Associate at the University of Colorado Boulder. Research in evolutionary biology, biological complexity, and macroecology.
theme: minima
show_downloads: false
google_analytics:
